### ISSUE TITLE
Problem in running ./test.sh on CPU

### ISSUE THREAD

**Issue by mhnasseri** [IPapakis/GCNNMatch#3]
Hi,
I want to run the code on the CPU. I could run ./train.sh. But there is a problem when I run ./test.sh. I have modified the load section of file tracking.py like this:
#load model
model = completeNet()
device = torch.device('cpu')	
model = model.to(device)
#model = DataParallel(model)
model.load_state_dict(torch.load('./models/epoch_11.pth', map_location=torch.device('cpu'))['model_state_dict'])  
model.eval()
When I run ./test.sh the following error is happened:
Traceback (most recent call last):
  File "./tracking.py", line 114, in <module>
    model.load_state_dict(loaded['model_state_dict'])  # map_location=torch.device('cpu')
  File "/home/mhnasseri/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for completeNet:
	Missing key(s) in state_dict: "cnn.cnn.0.conv0.weight", "cnn.cnn.0.norm0.weight", ...
How could I solve the problem to run the code on the CPU?

**Comment by mhnasseri** [comment]
Fortunately, I found the work around to solve the above problem. I have changed the load model section as below:
`
#load model
model = completeNet()
device = torch.device('cpu')	
model = model.to(device)
#model = DataParallel(model)  
# original saved file with DataParallel
state_dict = torch.load('./models/epoch_11.pth', map_location=torch.device('cpu'))['model_state_dict']   
# create new OrderedDict that does not contain `module.`
from collections import OrderedDict
new_state_dict = OrderedDict()
for k, v in state_dict.items():
    name = k[7:] # remove `module.`
    new_state_dict[name] = v
# load params
model.load_state_dict(new_state_dict) 
model.eval()
` 
Now, the load model part is run properly, but when I run ./test.sh, the following error is happened:
`
Sequence: 01
Total frames: 450.0
Sequence: 01, Frame: 2/450
Traceback (most recent call last):
  File "./tracking.py", line 138, in <module>
    tracking_output= model_testing(seq[s], detections, images_path, total_frames, frames_look_back, model, distance_limit, fp_min_times_seen, match_thres, det_conf_thres, fp_look_back, fp_recent_frame_limit, min_height, fps[s])
  File "/home/mhnasseri/Works/GCNNMatch-master/model_testing.py", line 89, in model_testing
    output, output2, ground_truth, ground_truth2, det_num, tracklet_num= model(batch)
  File "/home/mhnasseri/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mhnasseri/Works/GCNNMatch-master/network/complete_net.py", line 33, in forward
    data.x, data.coords_original, data.edge_index, data.ground_truth, data.coords, data.edges_number, data.frame, data.track_num, data.det_num
AttributeError: 'list' object has no attribute 'x'
`
What is the problem and how could I solve it?
